name: okepoint
description: Share location.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  # firebase services
  firebase_core_platform_interface: ^4.5.3

  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.1

  # state managers
  flutter_riverpod: ^2.3.6 # https://pub.dev/packages/flutter_riverpod

  # navigation
  go_router: ^9.0.3 # https://pub.dev/packages/go_router

  # UI
  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
